#!/usr/bin/env python3
"""Generate a fail-closed ledger committer for a verified continuation.

A checkpoint produced by a cumulative prefix contains an action-identity table
whose length is exactly that prefix.  The original committer therefore cannot
index the first continuation action.  This tool first runs the complete
continuation preflight, then emits the remaining manifest-derived ledger
deltas and a sequential committer that shares the checkpoint's existing event
and loaded-file state.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import sys
from typing import Any

import verify_flyspeck_continuation as preflight


def load_runtime(path: Path) -> Any:
    spec = importlib.util.spec_from_file_location(
        "_candle_continuation_ledger_runtime", path,
    )
    if spec is None or spec.loader is None:
        raise preflight.PreflightError("could not load stratum runtime")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while block := stream.read(1024 * 1024):
            digest.update(block)
    return digest.hexdigest()


def ml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render(
    manifest: dict[str, Any],
    runtime: Any,
    start: int,
    end: int,
    continuation_sha256: str,
    manifest_sha256: str,
    projection_sha256: str,
) -> str:
    nodes = manifest["source_nodes"]
    deltas = runtime.derive_action_ledger_delta_keys(manifest, end + 1)
    lines = [
        "(* Generated by candle/build_flyspeck_continuation_ledger.py.",
        "   The complete continuation passed the authoritative manifest preflight.",
        f"   continuation sha256: {continuation_sha256}",
        f"   manifest sha256: {manifest_sha256}",
        f"   action projection sha256: {projection_sha256}",
        "*)",
        "",
        f"let candle_flyspeck_continuation_start = {start};;",
        f"let candle_flyspeck_continuation_end = {end};;",
        "",
        "let candle_flyspeck_continuation_ledger_deltas = [",
    ]
    for index in range(start, end + 1):
        lines.append("  [")
        for key in deltas[index]:
            node = nodes[key]
            lines.append(
                "    (" + ml_string(Path(node["path"]).name) + "," +
                ml_string(node["md5"]) + ");"
            )
        lines.append("  ];")
    lines.extend([
        "];;",
        "",
        "if List.length candle_flyspeck_continuation_ledger_deltas <>",
        "     candle_flyspeck_continuation_end -",
        "     candle_flyspeck_continuation_start + 1",
        "then failwith \"Flyspeck continuation ledger cardinality mismatch\";;",
        "",
        "let candle_flyspeck_continuation_remaining_deltas =",
        "  ref candle_flyspeck_continuation_ledger_deltas;;",
        "",
        "let candle_flyspeck_continuation_commit_action",
        "    index expected_identity marker =",
        "  if index <> List.length !candle_flyspeck_stratum_action_events then",
        "    failwith \"Flyspeck continuation action event index mismatch\"",
        "  else if index < candle_flyspeck_continuation_start ||",
        "          index > candle_flyspeck_continuation_end then",
        "    failwith \"Flyspeck continuation action index out of range\"",
        "  else",
        "    match !candle_flyspeck_continuation_remaining_deltas with",
        "    | [] -> failwith \"Flyspeck continuation ledger exhausted\"",
        "    | expected_delta::remaining ->",
        "        (match expected_delta with",
        "         | [] -> failwith \"Flyspeck continuation action has an empty ledger delta\"",
        "         | outer_identity::_ ->",
        "             if outer_identity <> expected_identity then",
        "               failwith \"Flyspeck continuation action identity mismatch\"",
        "             else",
        "               let previous = !candle_flyspeck_stratum_previous_loaded_files in",
        "               let current = !loaded_files in",
        "               let outcome =",
        "                 if current = previous then",
        "                   if not (List.mem expected_identity previous) then",
        "                     failwith",
        "                       \"Flyspeck continuation action was skipped without its logical identity\"",
        "                   else if expected_delta <> [expected_identity] then",
        "                     failwith",
        "                       \"Flyspeck continuation action skipped its nested ledger delta\"",
        "                   else \"skip-ledger\"",
        "                 else if not (List.mem expected_identity previous) &&",
        "                         current = expected_delta @ previous then \"load\"",
        "                 else failwith",
        "                   \"Flyspeck continuation action has an unexpected loader identity delta\" in",
        "               candle_flyspeck_stratum_action_events :=",
        "                 (index,expected_identity,expected_delta,outcome) ::",
        "                 !candle_flyspeck_stratum_action_events;",
        "               candle_flyspeck_stratum_previous_loaded_files := current;",
        "               candle_flyspeck_continuation_remaining_deltas := remaining;",
        "               print_endline (marker ^ \" \" ^ outcome));;",
        "",
    ])
    return "\n".join(lines)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("continuation", type=Path)
    parser.add_argument("--manifest", type=Path, default=preflight.DEFAULT_MANIFEST)
    parser.add_argument("--runtime", type=Path, default=preflight.DEFAULT_RUNTIME)
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--overlay-root", type=Path, required=True)
    parser.add_argument("--expected-start", type=int, required=True)
    parser.add_argument("--expected-end", type=int, required=True)
    parser.add_argument("--attempt-nonce", required=True)
    parser.add_argument("--expected-existing-overlay-count", type=int, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    receipt = preflight.verify(args)
    manifest_path = args.manifest.resolve(strict=True)
    runtime_path = args.runtime.resolve(strict=True)
    continuation_path = args.continuation.resolve(strict=True)
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    runtime = load_runtime(runtime_path)
    output = render(
        manifest,
        runtime,
        args.expected_start,
        args.expected_end,
        sha256(continuation_path),
        sha256(manifest_path),
        receipt["continuation"]["action_projection_sha256"],
    )
    args.output.write_text(output, encoding="utf-8")
    print(json.dumps({
        "actions": args.expected_end - args.expected_start + 1,
        "output": str(args.output),
        "output_sha256": sha256(args.output),
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
