(* Generated by candle/flyspeck_manifest.py; do not edit.
   #flyspeck_needs is fail-closed until Candle implements the exact
   manifest-rooted load-and-neutralize action recorded in
   candle/flyspeck_manifest.json. *)

(* stratum: base *)
(* 000 selected=flyspeck:text_formalization/general/hol_pervasives.hl sha256=d9a64b56a366a45b5caa587000eb54963606e223f8a5f772aa9c1b98a54627e2 *)
#flyspeck_needs "general/hol_pervasives.hl";;
(* 001 selected=flyspeck:text_formalization/general/lib.hl sha256=a429247955e1e095e5663813e9609c43697d83d80f357c7855af3b76a3145865 *)
#flyspeck_needs "general/lib.hl";;
(* 002 selected=flyspeck:text_formalization/general/flyspeck_lib.hl sha256=2ae1a0d173275035c4e418e9aa314654edfe38db5619eb75292a8cbac3106de5 *)
#flyspeck_needs "general/flyspeck_lib.hl";;
(* 003 selected=flyspeck:text_formalization/general/print_types.hl sha256=193abcdff7657f421398203c67e67d32ce5204ce4ba5a04adad53f37fd161ae6 *)
#flyspeck_needs "general/print_types.hl";;
(* 004 selected=flyspeck:text_formalization/general/sphere.hl sha256=3ca15c5381194f63bb1d467b7d3a0ef3560e16769fac03b0f96d7aa9da514f32 *)
#flyspeck_needs "general/sphere.hl";;
(* 005 selected=flyspeck:text_formalization/general/hales_tactic.hl sha256=2f066101a59c74dd24c48985413534e653c90f96b82d97f8422aa5335d1c8408 *)
#flyspeck_needs "general/hales_tactic.hl";;
(* 006 selected=flyspeck:text_formalization/general/truong_tactic.hl sha256=5491a391c6e4925384eda9b5edb9fc888aa13dbf0aef93b31594770b28908548 *)
#flyspeck_needs "general/truong_tactic.hl";;
(* 007 selected=flyspeck:text_formalization/leg/basics.hl sha256=76c152b020418c2f96652f6315db885640239443aeab1d9ed4bb7e29338bafe1 *)
#flyspeck_needs "leg/basics.hl";;
(* 008 selected=flyspeck:text_formalization/leg/geomdetail.hl sha256=5bcfb9ff854af6665404ca6afeee82cf1e64dada3f8620d00321246074c1b8f4 *)
#flyspeck_needs "leg/geomdetail.hl";;
(* 009 selected=flyspeck:text_formalization/leg/AFF_SGN_TAC.hl sha256=01ac4b51202cd509f8f21000ad5220bb66b36c2ecc5760a47c98cfb3cead61a5 *)
#flyspeck_needs "leg/AFF_SGN_TAC.hl";;
(* 010 selected=flyspeck:text_formalization/leg/affprops.hl sha256=381383bb50f0ed351d79f078fc3d76ea5b870f25e4ba40aafde65b507ab0c303 *)
#flyspeck_needs "leg/affprops.hl";;
(* 011 selected=flyspeck:text_formalization/leg/cayleyR_def.hl sha256=3b5a8c44efe2d46f39fdf3bb7bc503926fd29bec280cb7fdcb6022ac2d05d5a7 *)
#flyspeck_needs "leg/cayleyR_def.hl";;
(* 012 selected=flyspeck:text_formalization/leg/muR_def.hl sha256=daa781a50d8f898944c6dd8eff0ce5ca0b0c1008663473e4b0221d83dacbcfab *)
#flyspeck_needs "leg/muR_def.hl";;
(* 013 selected=flyspeck:text_formalization/leg/enclosed_def.hl sha256=b4c23ee653be59c0ff653e159cabab9cb22b185e44cc8fcceeb1bae5c38bbcb1 *)
#flyspeck_needs "leg/enclosed_def.hl";;
(* 014 selected=flyspeck:text_formalization/leg/collect_geom.hl sha256=483ec7371a944a8d37cf7ca0d9c138c6492ec13c44c26298d0d97a84288dbf3b *)
#flyspeck_needs "leg/collect_geom.hl";;
(* 015 selected=flyspeck:text_formalization/leg/collect_geom2.hl sha256=39381f07853656cd59be5f8a866b27cf59ffadd3e482d59eeb3544b4e788bc77 *)
#flyspeck_needs "leg/collect_geom2.hl";;
(* 016 selected=flyspeck:text_formalization/jordan/refinement.hl sha256=83d7784b28176a16f578d2e31e3756bf99464d92dbed64626b647d2839211713 *)
#flyspeck_needs "jordan/refinement.hl";;
(* 017 selected=flyspeck:text_formalization/jordan/lib_ext.hl sha256=2b9d1421d35e124cee6c852ccf91294d1049f380af7bb2332116bdb47217787c *)
#flyspeck_needs "jordan/lib_ext.hl";;
(* 018 selected=flyspeck:text_formalization/jordan/hash_term.hl sha256=04872c1fb60f0c8d86b345a6027a547144c535524c53b49ebe8555b6bcaac32d *)
#flyspeck_needs "jordan/hash_term.hl";;
(* 019 selected=flyspeck:text_formalization/jordan/parse_ext_override_interface.hl sha256=32219be7380001d7318b4d71a658a1f2d827b7b25389f7d4f3d260f82bab965f *)
#flyspeck_needs "jordan/parse_ext_override_interface.hl";;
(* 020 selected=flyspeck:text_formalization/jordan/goal_printer.hl sha256=530a915c4f08ef6e46ed10bc8605497947c1cc4c77c9e9d46c59438d0e19bd6b *)
#flyspeck_needs "jordan/goal_printer.hl";;
(* 021 selected=flyspeck:text_formalization/jordan/real_ext.hl sha256=07038124181fadb80326312d889390b93289fba28e1525dc3346adf24833edc4 *)
#flyspeck_needs "jordan/real_ext.hl";;
(* 022 selected=flyspeck:text_formalization/jordan/tactics_jordan.hl sha256=3af61cf6961097eae9b67f3f3aaeef8fbd8c9a2ec2dfef1e95594561bac58ebe *)
#flyspeck_needs "jordan/tactics_jordan.hl";;
(* 023 selected=flyspeck:text_formalization/jordan/num_ext_nabs.hl sha256=883ad0bc9adc88d392e652491c19e91697a158627c7774e8b2a54bf109771b59 *)
#flyspeck_needs "jordan/num_ext_nabs.hl";;
(* 024 selected=flyspeck:text_formalization/jordan/taylor_atn.hl sha256=7c043950b28277db6bc698773e15462f2c3722ec9bc7a92ed8e0c4ae0ddb71c1 *)
#flyspeck_needs "jordan/taylor_atn.hl";;
(* 025 selected=flyspeck:text_formalization/jordan/float.hl sha256=11ea4ae6f28b1d12d4c7d6339342362fb5b261b2bfa17f64cd43579c3761a776 *)
#flyspeck_needs "jordan/float.hl";;
(* 026 selected=flyspeck:text_formalization/jordan/flyspeck_constants.hl sha256=c43c8b80c23c7e94ab50cf34d8332f3984bbf9499b07ecc694af4fb9093a0149 *)
#flyspeck_needs "jordan/flyspeck_constants.hl";;
(* 027 selected=flyspeck:text_formalization/jordan/misc_defs_and_lemmas.hl sha256=6c5de278e41d7ad799bacb079e387f347aaa0cd2bfd6682d74ce979fb536b125 *)
#flyspeck_needs "jordan/misc_defs_and_lemmas.hl";;
(* 028 selected=flyspeck:text_formalization/general/tactics.hl sha256=45cfef5bf4ca0fea5f1f9c59a4e8d0d56f569accaffe4b7f0d8fbf46dd42b7ba *)
#flyspeck_needs "general/tactics.hl";;
(* 029 selected=flyspeck:text_formalization/general/vukhacky_tactics.hl sha256=08cd45ed73e25b32a3398bc2c6c4b5b0428ed13d8f5385ce2d9db6e941b45518 *)
#flyspeck_needs "general/vukhacky_tactics.hl";;

(* stratum: arithmetic *)
(* 030 selected=flyspeck:text_formalization/trigonometry/trig1.hl sha256=18c28fa59364b83c9f91111475ffdd292e037685fd1e3160eac41c016ac1ae78 *)
#flyspeck_needs "trigonometry/trig1.hl";;
(* 031 selected=flyspeck:text_formalization/trigonometry/trig2.hl sha256=04c091bf919e4d590d5e53252333dfa8259a9a28d76013680486565d0ba5ab56 *)
#flyspeck_needs "trigonometry/trig2.hl";;
(* 032 selected=flyspeck:text_formalization/trigonometry/delta_x.hl sha256=2009822be120f6e1e6b1e2f60c6533cf17b53ec93a3c09664eebb1b46e36f2d2 *)
#flyspeck_needs "trigonometry/delta_x.hl";;
(* 033 selected=flyspeck:text_formalization/trigonometry/euler_complement.hl sha256=f6a097cae1dfa8c8736863604cff648f96570830e628c9b577afb48e8c49a679 *)
#flyspeck_needs "trigonometry/euler_complement.hl";;
(* 034 selected=flyspeck:text_formalization/trigonometry/euler_multivariate.hl sha256=4235b52fc6bef230970587c3b3b9ca70491d67f58b7ddfa1fd988d64dd65ea12 *)
#flyspeck_needs "trigonometry/euler_multivariate.hl";;
(* 035 selected=flyspeck:text_formalization/trigonometry/euler_main_theorem.hl sha256=1d36410277ab60f6500d59cd68b2ebb22a9492cff24c21cdf057d8abc0887397 *)
#flyspeck_needs "trigonometry/euler_main_theorem.hl";;
(* 036 selected=flyspeck:text_formalization/trigonometry/trig3.hl sha256=646ab4839ec3cf90859f053d7807372c9948629a53ab187cdf633aa11f1eb4fc *)
#flyspeck_needs "trigonometry/trig3.hl";;
(* 037 selected=flyspeck:text_formalization/trigonometry/HVIHVEC.hl sha256=db0c87ea8f440df0b841c5f0e625ae8d6f7a645082776ab30026b974b0550271 *)
#flyspeck_needs "trigonometry/HVIHVEC.hl";;

(* stratum: nonlinear_support *)
(* 038 selected=flyspeck:text_formalization/nonlinear/calc_derivative.hl sha256=b34c63e9e7005a32dd536b40d0ef4bfc8cade31bdbba7eb3fdaf93617c7dd83a *)
#flyspeck_needs "nonlinear/calc_derivative.hl";;
(* 039 selected=flyspeck:text_formalization/nonlinear/ineqdata3q1h.hl sha256=681b98b6fbc836d696297f960b7650b13be6be9ce9868af0e929ed8573186605 *)
#flyspeck_needs "nonlinear/ineqdata3q1h.hl";;
(* 040 selected=flyspeck:text_formalization/nonlinear/types.hl sha256=675d1cfd4565e677d698903df066d6197781abc402d0bb56ca6efc797ce19dea *)
#flyspeck_needs "nonlinear/types.hl";;
(* 041 selected=flyspeck:text_formalization/nonlinear/nonlin_def.hl sha256=a5f9c3edceed3d64c79bccad05db5b1e960346571d92f9ab3dd8981c43113a1f *)
#flyspeck_needs "nonlinear/nonlin_def.hl";;
(* 042 selected=flyspeck:text_formalization/nonlinear/ineq.hl sha256=d1160305349bbe0af190e78e178169f5b9165fbc7b5e9f83156094b1afeb2c68 *)
#flyspeck_needs "nonlinear/ineq.hl";;
(* 043 selected=flyspeck:text_formalization/nonlinear/main_estimate_ineq.hl sha256=ca0b086d9e4f4ae1f371209ecc94aae7b8f29a663d1a2e8026698f594d468220 *)
#flyspeck_needs "nonlinear/main_estimate_ineq.hl";;
(* 044 selected=flyspeck:text_formalization/nonlinear/nonlinear_lemma.hl sha256=a80506d08b71b081f0d011f048d83c80c51e5eb6e479361c77762b6d2079cdeb *)
#flyspeck_needs "nonlinear/nonlinear_lemma.hl";;
(* 045 selected=flyspeck:text_formalization/nonlinear/functional_equation.hl sha256=cbf99bdf7bb15a14cd302670012468cb2dff24546044ae827f524a240fe090a3 *)
#flyspeck_needs "nonlinear/functional_equation.hl";;
(* 046 selected=flyspeck:text_formalization/nonlinear/parse_ineq.hl sha256=14405601d8c38ef491248a9f76cd666f5b61ca0a50bce4fd7b3d05bf1e3982ee *)
#flyspeck_needs "nonlinear/parse_ineq.hl";;
(* 047 selected=flyspeck:text_formalization/nonlinear/optimize.hl sha256=dc2f9864b28be8ad3afde4fd99b3053828f0fe41bd5034e7d7a29997a177970b *)
#flyspeck_needs "nonlinear/optimize.hl";;
(* 048 selected=flyspeck:text_formalization/nonlinear/function_list.hl sha256=3bb151da37f2541c04bf4ba745ea5d5d3a0a7abc5c48b72ef2d944b5d7629941 *)
#flyspeck_needs "nonlinear/function_list.hl";;
(* 049 selected=flyspeck:text_formalization/nonlinear/merge_ineq.hl sha256=81771a544ca3485abe52e6989db3ce6d4a64b6f25e9893e9043981c83770be58 *)
#flyspeck_needs "nonlinear/merge_ineq.hl";;

(* stratum: analysis *)
(* 050 selected=flyspeck:text_formalization/volume/vol1.hl sha256=a7ddeae75143c842ac30633daa9dde8ba0cfc081d179b04b05a29b773bf12a7c *)
#flyspeck_needs "volume/vol1.hl";;
(* 051 selected=flyspeck:text_formalization/hypermap/hypermap.hl sha256=ddbb89012f7fe13064cabd16eb94e3667d0dcff76340717a9db8dea91ae14b08 *)
#flyspeck_needs "hypermap/hypermap.hl";;
(* 052 selected=flyspeck:text_formalization/fan/fan_defs.hl sha256=18d9c204eb065e371fb3ab27612103cb8e5ca339819b957b11ebb55cd20ff2cc *)
#flyspeck_needs "fan/fan_defs.hl";;
(* 053 selected=flyspeck:text_formalization/fan/fan.hl sha256=210a09b4a338ef9960b83f00f03a2957ea6664ba7314c79e5730a01f5301412f *)
#flyspeck_needs "fan/fan.hl";;
(* 054 selected=flyspeck:text_formalization/fan/GMLWKPK.hl sha256=0221bb5f7406793fb2fcc4c24b230b5359b41df93e6c0f4806d920f785a2cef2 *)
#flyspeck_needs "fan/GMLWKPK.hl";;
(* 055 selected=flyspeck:text_formalization/fan/topology.hl sha256=2ae70956e31a8e226105e614f7c23854db159caee198eb0e8d24561ae6066c55 *)
#flyspeck_needs "fan/topology.hl";;
(* 056 selected=flyspeck:text_formalization/fan/fan_misc.hl sha256=a6e0be3b58734fbc4f08054dda87aa7c2c40bdeb7b6091fec0230bff88349daa *)
#flyspeck_needs "fan/fan_misc.hl";;
(* 057 selected=flyspeck:text_formalization/fan/planarity.hl sha256=410d30c68f50cac5b24b868d5c4303e10ff5412867aa503c955c73436b9ffe6b *)
#flyspeck_needs "fan/planarity.hl";;
(* 058 selected=flyspeck:text_formalization/fan/hypermap_and_fan.hl sha256=64a481043a6b5d4056264419856e12b75ce921747f2f54f8c09f8e2784fae22b *)
#flyspeck_needs "fan/hypermap_and_fan.hl";;
(* 059 selected=flyspeck:text_formalization/fan/Conforming.hl sha256=b056098535a5961667b27405c18d6a3cf45c690200a8d26a3e51ac1876f5d9b9 *)
#flyspeck_needs "fan/Conforming.hl";;
(* 060 selected=flyspeck:text_formalization/fan/polyhedron.hl sha256=0790e3acec2550e76f553198c7b80484bb09b7be7d93d98e23e9e50e56cc55bb *)
#flyspeck_needs "fan/polyhedron.hl";;

(* stratum: geometry *)
(* 061 selected=flyspeck:text_formalization/packing/pack1.hl sha256=473ff83dc3a11fbc5282aa035f7ce5d164eed5634066e98479eddbbbc6244ed8 *)
#flyspeck_needs "packing/pack1.hl";;
(* 062 selected=flyspeck:text_formalization/packing/pack2.hl sha256=7baa871821bbdb7e03df774104a200540813c7cb0f2c1cc6b43f4da8a27c42a2 *)
#flyspeck_needs "packing/pack2.hl";;
(* 063 selected=flyspeck:text_formalization/packing/pack_defs.hl sha256=c6df87776dcb07b40052f3967bb550df82b2d3f19e2018a1c272de9a1cfd3bac *)
#flyspeck_needs "packing/pack_defs.hl";;
(* 064 selected=flyspeck:text_formalization/packing/pack_concl.hl sha256=130da12794c15bc7d8876b970445b8d53f521034088b43b9c9cc97ef17a10488 *)
#flyspeck_needs "packing/pack_concl.hl";;
(* 065 selected=flyspeck:text_formalization/packing/pack3.hl sha256=d3ceb82fb538a7529e9ef689e17698cb36148c46a063c192f8b305c70d98cc81 *)
#flyspeck_needs "packing/pack3.hl";;
(* 066 selected=flyspeck:text_formalization/packing/Rogers.hl sha256=4aa725bb9f7838b463f2da2e6fd4b1344b0a6df095f2cd3bd0ff17503ad97e9d *)
#flyspeck_needs "packing/Rogers.hl";;
(* 067 selected=flyspeck:text_formalization/packing/TARJJUW.hl sha256=121ecc5bb2e9579db867fa651c2fbfa188ef2e41e2c80fcf9c39aa4f39b3b770 *)
#flyspeck_needs "packing/TARJJUW.hl";;
(* 068 selected=flyspeck:text_formalization/packing/marchal1.hl sha256=c15142bcea79da96950f5803492193e1ed5f405cba22078fe9a2479ee2aa955a *)
#flyspeck_needs "packing/marchal1.hl";;
(* 069 selected=flyspeck:text_formalization/packing/UPFZBZM_support_lemmas.hl sha256=b4ed5b7bf67ca601eb60cc174fcfc21fc015351723480c1291bdd3330b31b41f *)
#flyspeck_needs "packing/UPFZBZM_support_lemmas.hl";;
(* 070 selected=flyspeck:text_formalization/packing/EMNWUUS.hl sha256=d9945fdd8f34300708c43cb0df4cbd832b02d196696b546650a012d317b7eff4 *)
#flyspeck_needs "packing/EMNWUUS.hl";;
(* 071 selected=flyspeck:text_formalization/packing/marchal2.hl sha256=e08f27210bd483556e17b77147a68e7f49d0cbd02d15344a3cbadf9e47747e1d *)
#flyspeck_needs "packing/marchal2.hl";;
(* 072 selected=flyspeck:text_formalization/packing/SLTSTLO.hl sha256=f3d683fb2d3d8b2f49cfea798f7cb66b8d20f23efb530bd1b86519727b70e346 *)
#flyspeck_needs "packing/SLTSTLO.hl";;
(* 073 selected=flyspeck:text_formalization/packing/LEPJBDJ.hl sha256=a54be35481632ac6261d9cb2886abd3ea471782daf7c538db13fd6272f2c0675 *)
#flyspeck_needs "packing/LEPJBDJ.hl";;
(* 074 selected=flyspeck:text_formalization/packing/URRPHBZ1.hl sha256=6762b21ad1f3ddcc11304a8e0be4ff412c8a7961a31ebe9a74f579b9c3db3599 *)
#flyspeck_needs "packing/URRPHBZ1.hl";;
(* 075 selected=flyspeck:text_formalization/packing/URRPHBZ2.hl sha256=2ccf6452614ebcf5a87d408f40ce9bbbb26ca113774cf1e9b517bffe93f881ce *)
#flyspeck_needs "packing/URRPHBZ2.hl";;
(* 076 selected=flyspeck:text_formalization/packing/HDTFNFZ.hl sha256=4c83f9e7645b639012b30e99d926cb004494c68d36c9d13cb8a1487f8008358e *)
#flyspeck_needs "packing/HDTFNFZ.hl";;
(* 077 selected=flyspeck:text_formalization/packing/URRPHBZ3.hl sha256=a19b00267a66c80bc44087135257cb84fcea3cc75909d403f1d3578e9866e396 *)
#flyspeck_needs "packing/URRPHBZ3.hl";;
(* 078 selected=flyspeck:text_formalization/packing/RVFXZBU.hl sha256=2181a59b2c3ab112f304b1fa5ad510c506c9c9a69d7a56b98483c0a4e310545f *)
#flyspeck_needs "packing/RVFXZBU.hl";;
(* 079 selected=flyspeck:text_formalization/local/WRGCVDR.hl sha256=9d1378418c444f1ec9ce63567cb085fd9def0142ef3a4fb203689e34b9bc636d *)
#flyspeck_needs "local/WRGCVDR.hl";;
(* 080 selected=flyspeck:text_formalization/local/LVDUCXU.hl sha256=0f0924d813bcd36df3ce9a0a48227b6076b1467967e02fb8dea1fb42554c6813 *)
#flyspeck_needs "local/LVDUCXU.hl";;
(* 081 selected=flyspeck:text_formalization/local/LDURDPN.hl sha256=8ebeec6c24f0f8bdfb1fb142cab4e0d8db17fbe3118b746d316ad057574abd56 *)
#flyspeck_needs "local/LDURDPN.hl";;
(* 082 selected=flyspeck:text_formalization/local/local_lemmas.hl sha256=935a70e862fd3783a73df0cc6bc5afca94f90fefeccb1c49696b75870a031990 *)
#flyspeck_needs "local/local_lemmas.hl";;
(* 083 selected=flyspeck:text_formalization/tame/Inequalities.hl sha256=cb89eb6e98594a2f3b76dd2f6ea5e26b5b1c948da617470fb462afa771ef58b4 *)
#flyspeck_needs "tame/Inequalities.hl";;
(* 084 selected=flyspeck:text_formalization/packing/YNHYJIT.hl sha256=6d4860d4777e5e73a255a2b26c2a006238169aeb6769ef1ccdfe3eeb525946cd *)
#flyspeck_needs "packing/YNHYJIT.hl";;
(* 085 selected=flyspeck:text_formalization/packing/NJIUTIU.hl sha256=d26ff18655cf7d9bcb8108d2c49564334b40318370c0a905bbf0bdeb421d5a39 *)
#flyspeck_needs "packing/NJIUTIU.hl";;
(* 086 selected=flyspeck:text_formalization/packing/TEZFFSK.hl sha256=32517cd3173965b89d1bdedd213fc4ed5b6ced6a266c6707bb10ad924cd098f5 *)
#flyspeck_needs "packing/TEZFFSK.hl";;
(* 087 selected=flyspeck:text_formalization/packing/QZKSYKG.hl sha256=1ddbfa237e8c044c741cfda169ea6e86d18bbc02db06bf7d4ea49fde448e8a72 *)
#flyspeck_needs "packing/QZKSYKG.hl";;
(* 088 selected=flyspeck:text_formalization/packing/DDZUPHJ.hl sha256=2618445d641ca5348e8101d1c54b2056a9120bd4a3238cf93f997c88da5ac1ac *)
#flyspeck_needs "packing/DDZUPHJ.hl";;
(* 089 selected=flyspeck:text_formalization/packing/AJRIPQN.hl sha256=692cab21cb7ce13343b4fcdfc8223dbfdc38aa556a958a903274aad93adfc56c *)
#flyspeck_needs "packing/AJRIPQN.hl";;
(* 090 selected=flyspeck:text_formalization/packing/QZYZMJC.hl sha256=7c83844660381ca4c4b4adb63736ea7dc320ea33d92625a70989b563158f44aa *)
#flyspeck_needs "packing/QZYZMJC.hl";;
(* 091 selected=flyspeck:text_formalization/packing/marchal3.hl sha256=191528d2c1dc3542751507d2b44880f3b4f07efe00ea9267b66bc10e28d21926 *)
#flyspeck_needs "packing/marchal3.hl";;
(* 092 selected=flyspeck:text_formalization/packing/GRUTOTI.hl sha256=bd9904546baab73ea85b01fd29237ceb10dd7259ce2aa1018747616ea1d4d875 *)
#flyspeck_needs "packing/GRUTOTI.hl";;
(* 093 selected=flyspeck:text_formalization/packing/KIZHLTL.hl sha256=ebfe07b419d7d8cef166894557707d02377fc4c34f7ed2a59e6009eea6132737 *)
#flyspeck_needs "packing/KIZHLTL.hl";;
(* 094 selected=flyspeck:text_formalization/packing/bump.hl sha256=0ced6ceabcc76baa3b3febdd3fd5fef01a0a9104bebc2364a6f731ad8493b0a9 *)
#flyspeck_needs "packing/bump.hl";;
(* 095 selected=flyspeck:text_formalization/packing/sum_gamma.hl sha256=81a39f9de73eb82bac78c954833e4d19418f1885e47511eb4e5081f1f0c1bbcc *)
#flyspeck_needs "packing/sum_gamma.hl";;
(* 096 selected=flyspeck:text_formalization/packing/UPFZBZM.hl sha256=625df4cd076adb2ec21ec55d8b0ca479225fc16e42e42f12ff9a9d3be3b73ad5 *)
#flyspeck_needs "packing/UPFZBZM.hl";;
(* 097 selected=flyspeck:text_formalization/packing/RDWKARC.hl sha256=249ed8c45b0aa6996a9fbe29e3ac2065458a5a5475d036e620e82e887b8494d1 *)
#flyspeck_needs "packing/RDWKARC.hl";;
(* 098 selected=flyspeck:text_formalization/local/local_lemmas1.hl sha256=7d9c55f3c978ea1f87ee27c8ac4b31275b6455bf261f59331cdf2c58d72c0c59 *)
#flyspeck_needs "local/local_lemmas1.hl";;
(* 099 selected=flyspeck:text_formalization/local/NKEZBFC.hl sha256=e8aebe835b91ad0b4f1ad3955588b9e0254e8ef847bf28b03114590713ac8396 *)
#flyspeck_needs "local/NKEZBFC.hl";;
(* 100 selected=flyspeck:text_formalization/tame/arc_properties.hl sha256=3bd55af541b82f7cd5dc54e56c9b0a381576f55d75c39cbfb33601fc0a0a1ce5 *)
#flyspeck_needs "tame/arc_properties.hl";;
(* 101 selected=flyspeck:text_formalization/fan/CFYXFTY.hl sha256=cbea26b38fedebbc09b294e49ecf97320e98c49d5b930d33b580b2bbc334e55e *)
#flyspeck_needs "fan/CFYXFTY.hl";;
(* 102 selected=flyspeck:text_formalization/packing/YSSKQOY.hl sha256=6b3757a817e166fd6876a7bdfb84e46417f961fa97c6ab5fc8dd58435dd42a4b *)
#flyspeck_needs "packing/YSSKQOY.hl";;
(* 103 selected=flyspeck:text_formalization/packing/counting_spheres.hl sha256=7e7d2b31f0044b199444ea6ef90056d266b759fd41bd6efcd60c87447b38b40b *)
#flyspeck_needs "packing/counting_spheres.hl";;
(* 104 selected=flyspeck:text_formalization/packing/REUHADY.hl sha256=e3e910ec4854a209098e2a8cf78c50e160e6396258ebc6ee83237ed83f0dd976 *)
#flyspeck_needs "packing/REUHADY.hl";;
(* 105 selected=flyspeck:text_formalization/packing/TSKAJXY1.hl sha256=2abbd44a13253fa20320df5e187e1d1be49e1846b517def8b2986aa04942d20f *)
#flyspeck_needs "packing/TSKAJXY1.hl";;
(* 106 selected=flyspeck:text_formalization/packing/TSKAJXY2.hl sha256=0f3c806418f5b4f6abcce0c0d1ed2d615d5877d5fac32d255d506bc8dff84181 *)
#flyspeck_needs "packing/TSKAJXY2.hl";;
(* 107 selected=flyspeck:text_formalization/packing/OXLZLEZ1.hl sha256=ced59cac0778459b6852a47676eeaea53ddda932ca080af34aae0be92959df7e *)
#flyspeck_needs "packing/OXLZLEZ1.hl";;
(* 108 selected=flyspeck:text_formalization/packing/OXLZLEZ2.hl sha256=8c068facbc067aa2990210e45c9945e7b010d1e150a6b623a59af5199a1a0235 *)
#flyspeck_needs "packing/OXLZLEZ2.hl";;
(* 109 selected=flyspeck:text_formalization/packing/leaf_cell.hl sha256=d9a4f7e3b1267848d46797374a123a6a240f648e647520c4d76862e9d9c3a845 *)
#flyspeck_needs "packing/leaf_cell.hl";;
(* 110 selected=flyspeck:text_formalization/packing/TSKAJXY3.hl sha256=59befc76172d9f334b26b01e6eec6c04a973fe3af0419918d4d9c2f21d3764f6 *)
#flyspeck_needs "packing/TSKAJXY3.hl";;
(* 111 selected=flyspeck:text_formalization/packing/OXLZLEZ3.hl sha256=57059269427de64128483e63dde33b9023a022fb90165bb28b1bc7a5c3f7cd82 *)
#flyspeck_needs "packing/OXLZLEZ3.hl";;
(* 112 selected=flyspeck:text_formalization/local/dih2k.hl sha256=ee6792a1d6817555dea8a802e11eda883aa25f0532b574649c652747fdf488a4 *)
#flyspeck_needs "local/dih2k.hl";;
(* 113 selected=flyspeck:text_formalization/local/WJSCPRO.hl sha256=79a084c0e8d5cc1e0f639ec790066fb0b2a2403892a78304a627b23dc12fcb33 *)
#flyspeck_needs "local/WJSCPRO.hl";;
(* 114 selected=flyspeck:text_formalization/local/TECOXBM.hl sha256=9456155a3bbd3a1477845c9279445f10e0e15566e50ad94d4e992fe59a34ed95 *)
#flyspeck_needs "local/TECOXBM.hl";;
(* 115 selected=flyspeck:text_formalization/local/VPWSHTO.hl sha256=2562f238f5bb108dccec46c7b1a743945532a5eb628834f3ed20d69c123ae534 *)
#flyspeck_needs "local/VPWSHTO.hl";;
(* 116 selected=flyspeck:text_formalization/local/LFJCIXP.hl sha256=0e60ed13184ee28a33be03bbe46418c2e5d466e510a0a377fed1e7aef5be95ec *)
#flyspeck_needs "local/LFJCIXP.hl";;
(* 117 selected=flyspeck:text_formalization/local/localization.hl sha256=d8c4377622d39658b1340583c37b33650adf51c9839d05e3ac3dc9aabf7ab0c3 *)
#flyspeck_needs "local/localization.hl";;
(* 118 selected=flyspeck:text_formalization/local/polar_fan.hl sha256=f56f25e9080cc7c06ce221ac469894d439cae04872d470113aea235951e29ac5 *)
#flyspeck_needs "local/polar_fan.hl";;
(* 119 selected=flyspeck:text_formalization/local/HDPLYGY.hl sha256=1244450fa369cc2dd67ee4bd6d3f711920d38791238a6bf3f2bfe1c98cb3a7f0 *)
#flyspeck_needs "local/HDPLYGY.hl";;
(* 120 selected=flyspeck:text_formalization/local/GBYCPXS.hl sha256=50ca107bfaa83e738ba203191fadc557c997a494f9f063273c6eb02fce00e732 *)
#flyspeck_needs "local/GBYCPXS.hl";;
(* 121 selected=flyspeck:text_formalization/local/MTUWLUN.hl sha256=aea977163589817685004679a7ea421a4a20b7c4f1565048de22768fd5e555fe *)
#flyspeck_needs "local/MTUWLUN.hl";;
(* 122 selected=flyspeck:text_formalization/local/PCRTTID.hl sha256=db764f43811a7c0ad3f824c5e57f60659d8342f03dc96e3d92aae917d4b69d1e *)
#flyspeck_needs "local/PCRTTID.hl";;
(* 123 selected=flyspeck:text_formalization/local/XIVPHKS.hl sha256=4ee389a4baa5a9dfa9586505c057a113ec00176380616c24c1db4c4c9a858ae0 *)
#flyspeck_needs "local/XIVPHKS.hl";;
(* 124 selected=flyspeck:text_formalization/tame/tame_defs.hl sha256=b2e249eba14d82d349ba4613d6655a7449de4225beb98f22de7c17c36424d5a5 *)
#flyspeck_needs "tame/tame_defs.hl";;
(* 125 selected=flyspeck:text_formalization/tame/tame_concl.hl sha256=bb3fc6d2a24788cfa9014282fa59b52b4dcb18013c1771c5f21349a8b2699145 *)
#flyspeck_needs "tame/tame_concl.hl";;
(* 126 selected=flyspeck:jHOLLight/caml/ssreflect.hl sha256=9fefd64395673d3813762b90f0c99e86942a29fd2b80d0725dab3ba15aba9ed9 *)
#flyspeck_needs "../jHOLLight/caml/ssreflect.hl";;
(* 127 selected=flyspeck:jHOLLight/caml/sections.hl sha256=05e435d55cada51b56fee84696fffe30b7e11b0010fb8a56061c2e9b2c815b51 *)
#flyspeck_needs "../jHOLLight/caml/sections.hl";;
(* 128 selected=flyspeck:jHOLLight/Examples/ssrfun-compiled.hl sha256=da8ee55c6fe95fb738429292b5dbcdf9bad6151d630148acf9f605f8ca604512 *)
#flyspeck_needs "../jHOLLight/Examples/ssrfun-compiled.hl";;
(* 129 selected=flyspeck:jHOLLight/Examples/ssrbool-compiled.hl sha256=24cd8ef9e253145b031b13e0d68250217ade43e583c21ee6574136aa0a120c97 *)
#flyspeck_needs "../jHOLLight/Examples/ssrbool-compiled.hl";;
(* 130 selected=flyspeck:jHOLLight/Examples/ssrnat-compiled.hl sha256=66e533d777177cb4149e7f958af68cfa8e28e0be117537b8b3f81ba50071c188 *)
#flyspeck_needs "../jHOLLight/Examples/ssrnat-compiled.hl";;
(* 131 selected=flyspeck:text_formalization/fan/hypermap_iso-compiled.hl sha256=2da3701d76d46ae96406b71a5934611bb66b12d1bc0ac511e15ace0806523755 *)
#flyspeck_needs "fan/hypermap_iso-compiled.hl";;
(* 132 selected=flyspeck:text_formalization/tame/CKQOWSA_3.hl sha256=6ee979ac5fa18f3e24912dc91ae99f99a0c6273e8dedff39faa1130793b1a899 *)
#flyspeck_needs "tame/CKQOWSA_3.hl";;
(* 133 selected=flyspeck:text_formalization/tame/CKQOWSA_4.hl sha256=2c767d5d471aa17a75be09382557314895cb2bfc3e59fa1d876f2cf3446b1561 *)
#flyspeck_needs "tame/CKQOWSA_4.hl";;
(* 134 selected=flyspeck:text_formalization/tame/CKQOWSA.hl sha256=72c8ceb7b828fef51d2f75fe2faef984331a4d60cb800e2c7140c12e4e0c6966 *)
#flyspeck_needs "tame/CKQOWSA.hl";;
(* 135 selected=flyspeck:text_formalization/tame/tame_general.hl sha256=a3700341cc9b9d4283e3224775680fcfab170143234523455308afbdbeff9717 *)
#flyspeck_needs "tame/tame_general.hl";;
(* 136 selected=flyspeck:text_formalization/tame/JGTDEBU.hl sha256=aa382862b721b25080f92a8be0fb9d62271be647da189cd443bf0880d03044f2 *)
#flyspeck_needs "tame/JGTDEBU.hl";;
(* 137 selected=flyspeck:text_formalization/tame/tame_opposite.hl sha256=23365d77b8c8a42a49bfbc4bfc42d4f8ea7a863cfbffa1822b21ae9080a1930e *)
#flyspeck_needs "tame/tame_opposite.hl";;
(* 138 selected=flyspeck:text_formalization/tame/FATUGPD.hl sha256=5cd05b29a62df7118cc5c3f1fd5143821067230fd46c90fcf080699864786a37 *)
#flyspeck_needs "tame/FATUGPD.hl";;
(* 139 selected=flyspeck:text_formalization/tame/CRTTXAT.hl sha256=5d19628b77329a2378d39064dbfd7d4de2701a5b5676757618d7a121d06aaa33 *)
#flyspeck_needs "tame/CRTTXAT.hl";;
(* 140 selected=flyspeck:text_formalization/tame/HRXEFDM.hl sha256=af29eef676209599749c097ac91f0ffd0b19f6e14479c559516ff831d3b6fa83 *)
#flyspeck_needs "tame/HRXEFDM.hl";;
(* 141 selected=flyspeck:jHOLLight/Examples/seq-compiled.hl sha256=ce054aa95c0bf0cb492ef11eb5291d085f7564eee98624564b75add785288b6a *)
#flyspeck_needs "../jHOLLight/Examples/seq-compiled.hl";;
(* 142 selected=flyspeck:text_formalization/tame/ssreflect/seq2-compiled.hl sha256=0a98ab2cb9847c23e0a78b4165d3ee7d911eb19a1392235c0263b6c7ac961bc6 *)
#flyspeck_needs "tame/ssreflect/seq2-compiled.hl";;
(* 143 selected=flyspeck:text_formalization/tame/ssreflect/sort-compiled.hl sha256=4276b638ad55dc99e9e61d729ae47fd8353d6867e589d5bfd52d6dd62d8ded93 *)
#flyspeck_needs "tame/ssreflect/sort-compiled.hl";;
(* 144 selected=flyspeck:text_formalization/tame/ssreflect/FNJLBXS-compiled.hl sha256=4074682366ef6f8fe0bca059801fca0414607a020a7a0d7b32ffca2931c80ef8 *)
#flyspeck_needs "tame/ssreflect/FNJLBXS-compiled.hl";;
(* 145 selected=flyspeck:formal_lp/hypermap/ssreflect/add_triangle-compiled.hl sha256=27fc827bef7c9cb76c01e0219a8126b7b56a6468dd61a66b95aba84c7ad6e847 *)
#flyspeck_needs "../formal_lp/hypermap/ssreflect/add_triangle-compiled.hl";;
(* 146 selected=flyspeck:text_formalization/tame/ssreflect/tame_lemmas-compiled.hl sha256=0bb81eb6efc0b7ddb380f3fe5c240b894e83bd0672960de54af5fc9072426ebb *)
#flyspeck_needs "tame/ssreflect/tame_lemmas-compiled.hl";;
(* 147 selected=flyspeck:text_formalization/tame/CDTETAT.hl sha256=7dc7ed63c36000faf6ef6e263f638caab8647a6f6fb8c0a5309f081f37008ff7 *)
#flyspeck_needs "tame/CDTETAT.hl";;
(* 148 selected=flyspeck:text_formalization/local/appendix.hl sha256=3759c7cfac842007bcde2f5c3ffcf04961934d44a1277029ee055320eaf19374 *)
#flyspeck_needs "local/appendix.hl";;
(* 149 selected=flyspeck:text_formalization/local/terminal.hl sha256=6d314b2c93d46a99bb3d77bd4ba0158fb00c77fd3f1ef97c423de8239800fb4f *)
#flyspeck_needs "local/terminal.hl";;
(* 150 selected=flyspeck:text_formalization/local/pent_hex.hl sha256=3be0e2e05a0f759c4ae6c3f7e04d72130353452a63519fc42793343590830488 *)
#flyspeck_needs "local/pent_hex.hl";;
(* 151 selected=flyspeck:text_formalization/local/lp_details.hl sha256=c2807eec8238ba324f7570dfd3dd03cc61f88f10b2d9bcb3309104cc805e000d *)
#flyspeck_needs "local/lp_details.hl";;

(* stratum: lp_support *)
(* 152 selected=flyspeck:formal_lp/hypermap/arith_link.hl sha256=c956e7ad601e860acb99b78652d27d701947c2f6e6b370d39103c1a20f841537 *)
#flyspeck_needs "../formal_lp/hypermap/arith_link.hl";;
(* 153 selected=flyspeck:formal_lp/glpk/glpk_link.ml sha256=cfef91db36d9c20e070ac467e981cd593c0ef623b68840de3e4f8d21811add66 *)
#flyspeck_needs "../formal_lp/glpk/glpk_link.ml";;
(* 154 selected=flyspeck:formal_graph/archive/archive_all.ml sha256=703ea865a124aa69f0ee12d94df7065bbbf5701a3085776e24632d14493474db *)
#flyspeck_needs "../formal_graph/archive/archive_all.ml";;
(* 155 selected=flyspeck:formal_lp/glpk/lpproc.ml sha256=b57ad6177c5c53ed7c35fdde5c11e1859445438325885ea235f97d5e910d73c8 *)
#flyspeck_needs "../formal_lp/glpk/lpproc.ml";;
(* 156 selected=flyspeck:formal_lp/hypermap/ssreflect/list_hypermap-compiled.hl sha256=9bc9f1f942bf055e0bea3fa10435b621e52458f435fc840bc670c51d648a67f5 *)
#flyspeck_needs "../formal_lp/hypermap/ssreflect/list_hypermap-compiled.hl";;
(* 157 selected=flyspeck:formal_lp/hypermap/ssreflect/list_hypermap_iso-compiled.hl sha256=4570334c652aedda6e4c2aa6d9582b5e4737cd87989cf173fdea4867f3b88a9e *)
#flyspeck_needs "../formal_lp/hypermap/ssreflect/list_hypermap_iso-compiled.hl";;
(* 158 selected=flyspeck:formal_lp/hypermap/ineqs/lp_ineqs_defs.hl sha256=1013104c8691fc94b3b4202d554cc518ae934c0e4a3b2579f66adce6f0432b6f *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_ineqs_defs.hl";;
(* 159 selected=flyspeck:formal_lp/ineqs/constants_approx.hl sha256=1a4271b07f67034781400fc06abc374b94cbc9c85433fb78ba2a32c89283dccb *)
#flyspeck_needs "../formal_lp/ineqs/constants_approx.hl";;
(* 160 selected=flyspeck:formal_lp/hypermap/ineqs/lp_ineqs_proofs-compiled.hl sha256=660fd87e5ef3ffbcc623c438a5d719456b558f9e51c198197ca6496c514fae4c *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_ineqs_proofs-compiled.hl";;
(* 161 selected=flyspeck:text_formalization/local/RNSYJXM-compiled.hl sha256=3c859bb8b1a0eb20fbc5799ed84a9657b775675f29601b1e826a4c670244bc32 *)
#flyspeck_needs "local/RNSYJXM-compiled.hl";;
(* 162 selected=flyspeck:formal_lp/hypermap/ineqs/lp_main_estimate-compiled.hl sha256=10e6a449605eab5f209d942e7e192ced7c70cba66f616acc314be1538ac0f5aa *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_main_estimate-compiled.hl";;
(* 163 selected=flyspeck:formal_lp/ineqs/delta_ineq.hl sha256=d1eb8eaaae32e600e200d5f16b782f9c678390d5997cec025c8964e484939063 *)
#flyspeck_needs "../formal_lp/ineqs/delta_ineq.hl";;
(* 164 selected=flyspeck:formal_lp/hypermap/ineqs/lp_ineqs_proofs2-compiled.hl sha256=dd2f76a67dff3c847c05932c574c0752a7fd6cc86ff95ad091c9ed7285c8442e *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_ineqs_proofs2-compiled.hl";;
(* 165 selected=flyspeck:formal_lp/hypermap/ineqs/lp_ineqs_quads-compiled.hl sha256=879bb59c3e98ac8c9e2d14deabaede782082178ff72bd0838994087c9015976c *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_ineqs_quads-compiled.hl";;
(* 166 selected=flyspeck:formal_lp/hypermap/computations/more_theory-compiled.hl sha256=7990e6c09e98d13ef4de216b18e051eaf2283ceae04ceb31550685e244d8c6b2 *)
#flyspeck_needs "../formal_lp/hypermap/computations/more_theory-compiled.hl";;
(* 167 selected=flyspeck:formal_lp/hypermap/ineqs/lp_gen_theory-compiled.hl sha256=aecda19251504176839a2ce11d95be727cacde86191805e13e48be25ad5d2010 *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_gen_theory-compiled.hl";;
(* 168 selected=flyspeck:formal_lp/hypermap/computations/list_conversions2.hl sha256=d85d504913e801edfa03ad0ea97373af0273ee9034bb573f8ca7cce142f9dac6 *)
#flyspeck_needs "../formal_lp/hypermap/computations/list_conversions2.hl";;
(* 169 selected=flyspeck:formal_lp/hypermap/computations/list_hypermap_computations.hl sha256=7be57bd195a33d815b6f9298a88c0acb7cf8e5b06460b3c5b3e25b5866308d83 *)
#flyspeck_needs "../formal_lp/hypermap/computations/list_hypermap_computations.hl";;
(* 170 selected=flyspeck:text_formalization/tame/good_list_archive.hl sha256=21125bc287b4fc28897ecf66df3f939718d1ecf1d086b25bed4cac6fc1a6493f *)
#flyspeck_needs "tame/good_list_archive.hl";;
(* 171 selected=flyspeck:formal_lp/hypermap/ineqs/lp_gen_ineqs.hl sha256=4f577e5ac7df1b409e5257d66d192b5dbbb577992bfc8834c7bc6df3c56c0f7d *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_gen_ineqs.hl";;
(* 172 selected=flyspeck:formal_lp/hypermap/ineqs/lp_approx_ineqs.hl sha256=7e95f3e742debc13a86d913067d3ed9de20066d538ce4e353b1d35c63a697265 *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_approx_ineqs.hl";;
(* 173 selected=flyspeck:formal_lp/hypermap/ineqs/lp_ineqs.hl sha256=3fb369d89d13c1dd04cb1710424d9b2f1943bc8b04a1f83128f716975ea09a1e *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_ineqs.hl";;
(* 174 selected=flyspeck:formal_lp/hypermap/ineqs/lp_head_ineqs.hl sha256=24441a19dfdec9d14f4f4048e7d93cdefd4ed2b29f028c0282f4a00f1b8044ba *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_head_ineqs.hl";;
(* 175 selected=flyspeck:formal_lp/hypermap/ineqs/lp_body_ineqs_data.hl sha256=bb9460c2285878efa7c473c06dd7b60494b8c560eb4ca0a1ec90a1291495c3d8 *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_body_ineqs_data.hl";;
(* 176 selected=flyspeck:formal_lp/hypermap/ineqs/lp_body_ineqs.hl sha256=d0783e75e9e3cc2d0a2009a50f4b7efcc9f6b783116ff6fee04167426e5a39a9 *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_body_ineqs.hl";;
(* 177 selected=flyspeck:formal_lp/hypermap/main/lp_certificate.hl sha256=256ad729d3e4138da4ee911d03d98ce04fac42f2df360252bf6a9c6badd52709 *)
#flyspeck_needs "../formal_lp/hypermap/main/lp_certificate.hl";;
(* 178 selected=flyspeck:formal_lp/hypermap/computations/informal_computations.hl sha256=fcf3cb31c7d15b5886ae40babb49672328181dcbbc9d47f081246faeadf0ed5a *)
#flyspeck_needs "../formal_lp/hypermap/computations/informal_computations.hl";;
(* 179 selected=flyspeck:formal_lp/more_arith/lin_f.hl sha256=468f17fe851a65d4c02d14abcb99655e3a8b051f8b9a1de1d222ef99ff404054 *)
#flyspeck_needs "../formal_lp/more_arith/lin_f.hl";;
(* 180 selected=flyspeck:formal_lp/more_arith/arith_int.hl sha256=6c9581a71f046ba90b6398a281e2a4e2cebc8b739be60d6ddb3e68da4ce5dc89 *)
#flyspeck_needs "../formal_lp/more_arith/arith_int.hl";;
(* 181 selected=flyspeck:formal_lp/more_arith/prove_lp.hl sha256=e43b85cb2e403458dd8715376d80862cd5ffa3a7007586521907c8f230d69c75 *)
#flyspeck_needs "../formal_lp/more_arith/prove_lp.hl";;
(* 182 selected=flyspeck:formal_lp/hypermap/main/prove_flyspeck_lp.hl sha256=8ed592aa6515b9fe76cef8f101c98953bfe53b21d0cf023ccb45aaa62f97cc3f normalization=PROJECT-POINTER-S3-IMMEDIATE-001 normalized_sha256=243a2031e595efa9bf0b85b552f9620f4ab45cbca8dcebef821f2eae68c3bba4 *)
#flyspeck_needs "../formal_lp/hypermap/main/prove_flyspeck_lp.hl";;
(* 183 selected=flyspeck:formal_lp/hypermap/verify_all.hl sha256=c81f340edda820f06c3f2db753e192fdd6288abb7b3c410c1c4a97299e76df95 *)
#flyspeck_needs "../formal_lp/hypermap/verify_all.hl";;
(* 184 selected=flyspeck:text_formalization/tame/linear_programming_results.hl sha256=0588a0006de8a863de1ad3f855104296233147b9805c87eaa82a6fa8f5b5c4d4 *)
#flyspeck_needs "tame/linear_programming_results.hl";;

(* stratum: text_formalization *)
(* 185 selected=flyspeck:text_formalization/local/ZITHLQN.hl sha256=34457e2cb251f4df3ba53a074306b91051a69e70b037af8b87952c8f8463bbdf *)
#flyspeck_needs "local/ZITHLQN.hl";;
(* 186 selected=flyspeck:text_formalization/local/XWITCCN.hl sha256=915146caef5905ec1553da862e3ba5b38789a7222844893261ce0907fcdf47a3 *)
#flyspeck_needs "local/XWITCCN.hl";;
(* 187 selected=flyspeck:text_formalization/local/AYQJTMD.hl sha256=5021a1261b8dd84d41c8abd24bb060ebdfb714db6d4bb546e61f117ed96db23b *)
#flyspeck_needs "local/AYQJTMD.hl";;
(* 188 selected=flyspeck:text_formalization/local/JKQEWGV.hl sha256=61fbbe1715129af2123c06cb95bcc32813a342bc73a749729a141eb9d1885d0e *)
#flyspeck_needs "local/JKQEWGV.hl";;
(* 189 selected=flyspeck:text_formalization/local/UXCKFPE.hl sha256=36da9559935508c3209df0ed8817e3ab271a7381e2a0319ecbec0cc132a238d1 *)
#flyspeck_needs "local/UXCKFPE.hl";;
(* 190 selected=flyspeck:text_formalization/local/SGTRNAF.hl sha256=47e875eebf7c287cf593c86d1cae3e1eed9bfed39490cdf6ea1649fc0b2fd177 *)
#flyspeck_needs "local/SGTRNAF.hl";;
(* 191 selected=flyspeck:text_formalization/local/QKNVMLB.hl sha256=be4e8bd03a4af084ee5184639a36f82647d34d8b78155ddbd343f12cdf632b48 *)
#flyspeck_needs "local/QKNVMLB.hl";;
(* 192 selected=flyspeck:text_formalization/local/YXIONXL.hl sha256=4baef3fe6317dcfc5aba6bf47159acfe2ede00451482334b807bddfb37649fbf *)
#flyspeck_needs "local/YXIONXL.hl";;
(* 193 selected=flyspeck:text_formalization/local/HXHYTIJ.hl sha256=ccbfc2580431f0be8bd4e5ee3de0b7670cd4462cd5adb4716e581e6d03d9b560 *)
#flyspeck_needs "local/HXHYTIJ.hl";;
(* 194 selected=flyspeck:text_formalization/local/UAGHHBM.hl sha256=6f307b987e8a2b17f564b5f135822b73192796f9eb4280ac810acef16b76cd2f *)
#flyspeck_needs "local/UAGHHBM.hl";;
(* 195 selected=flyspeck:text_formalization/local/LKGRQUI.hl sha256=834b7c2c0dbd1b603099706c2bf87ee4f82b60932be1b4611ce0baa5d9e0931a *)
#flyspeck_needs "local/LKGRQUI.hl";;
(* 196 selected=flyspeck:text_formalization/local/deformation.hl sha256=375229b9160f6c3914662ec2ce292adc68baeeb61efeb232f5b3f39f22147d8c *)
#flyspeck_needs "local/deformation.hl";;
(* 197 selected=flyspeck:text_formalization/local/ODXLSTC.hl sha256=0909ee8200385851d11c0b63537b4e1d2f72b052d482b423efa6005a717f6298 *)
#flyspeck_needs "local/ODXLSTC.hl";;
(* 198 selected=flyspeck:text_formalization/local/lunar_deform.hl sha256=9b54a762b48d53afb781f8982fd228ac878f5226674875966ee1e13cd2b51aaa *)
#flyspeck_needs "local/lunar_deform.hl";;
(* 199 selected=flyspeck:text_formalization/local/OCBICBY.hl sha256=9f0d93d5e017b2da30661dc5b2dfb6777945b392b850955b2b08b20bb8847bd1 *)
#flyspeck_needs "local/OCBICBY.hl";;
(* 200 selected=flyspeck:text_formalization/local/YXIONXL2.hl sha256=c1498031007532b0f044941ccc02efd0a468d3f799d98fd86f272681c86f8cc4 *)
#flyspeck_needs "local/YXIONXL2.hl";;
(* 201 selected=flyspeck:text_formalization/local/EYYPQDW.hl sha256=22b0b16365e19adb9a128dd272f741f8b5b8ec1cdf3450a526e52474d0ace9fa *)
#flyspeck_needs "local/EYYPQDW.hl";;
(* 202 selected=flyspeck:text_formalization/local/IMJXPHR.hl sha256=7a15d273f88363c3102f32138fdb8a446cde3bc16cea74ff9a1a513d1effe39e *)
#flyspeck_needs "local/IMJXPHR.hl";;
(* 203 selected=flyspeck:text_formalization/local/ZLZTHIC.hl sha256=ee0bbc735edc2796b580bf21b5243ed66a17d0d84e2d3808de4a58e38a026081 *)
#flyspeck_needs "local/ZLZTHIC.hl";;
(* 204 selected=flyspeck:text_formalization/local/PQCSXWG.hl sha256=31ed2899306045b472d28ee5a39d3cfc06ee3522c3982efc572da32b3d1946aa *)
#flyspeck_needs "local/PQCSXWG.hl";;
(* 205 selected=flyspeck:text_formalization/local/NUXCOEA.hl sha256=c8faad3618eec267bcb1598ad7bd3b2974796dd301b2c6de65ee7bcf4b6af1ab *)
#flyspeck_needs "local/NUXCOEA.hl";;
(* 206 selected=flyspeck:text_formalization/local/FEKTYIY.hl sha256=28f1fbd17f96176c211d7e9af59ac6f17607a76d781294bb512580795207c6de *)
#flyspeck_needs "local/FEKTYIY.hl";;
(* 207 selected=flyspeck:text_formalization/local/AURSIPD.hl sha256=915513130137830b0b7a3c8582cacaf0ed17da908b6353d41ac1b6ced0904a80 *)
#flyspeck_needs "local/AURSIPD.hl";;
(* 208 selected=flyspeck:text_formalization/local/PPBTYDQ.hl sha256=46ea67929dee68670c52d0c091c425c70d995ce8a6cee394929fa0a640b7b68f *)
#flyspeck_needs "local/PPBTYDQ.hl";;
(* 209 selected=flyspeck:text_formalization/local/AXJRPNC.hl sha256=bb4f6a44c3844ce5eea2cbe82acb7181f5d441aac31af3778873dc06e4975687 *)
#flyspeck_needs "local/AXJRPNC.hl";;
(* 210 selected=flyspeck:text_formalization/local/CUXVZOZ.hl sha256=4a65141718b108636a88712c8fb4a545bb0f68a97ff4cc98ea128ea380cd181a *)
#flyspeck_needs "local/CUXVZOZ.hl";;
(* 211 selected=flyspeck:text_formalization/local/RRCWNSJ.hl sha256=9964494aa8a485acb814f83b80ce42f7e67195db76b6e2e0b298dd99181b5538 *)
#flyspeck_needs "local/RRCWNSJ.hl";;
(* 212 selected=flyspeck:text_formalization/local/JCYFMRP.hl sha256=6ec56682f4d71be7eaf1e743d81a04fa399977274fc825548dc5b582fa0c1178 *)
#flyspeck_needs "local/JCYFMRP.hl";;
(* 213 selected=flyspeck:text_formalization/local/TFITSKC.hl sha256=e728191705635b29beb79610fcd76e407e9e8480276afe031f2fb48acbcc6aac *)
#flyspeck_needs "local/TFITSKC.hl";;
(* 214 selected=flyspeck:text_formalization/local/CQAOQLR.hl sha256=5816a0184adda05da90d30a3fd856c2a49b502ed4fc2be67782ddd201a80dc71 *)
#flyspeck_needs "local/CQAOQLR.hl";;
(* 215 selected=flyspeck:text_formalization/local/JLXFDMJ.hl sha256=c44d861dca28da7e8cf9b4cc501f8ef0a25d1df83dcb77c1a9ed9834289f80fc *)
#flyspeck_needs "local/JLXFDMJ.hl";;
(* 216 selected=flyspeck:text_formalization/local/YRTAFYH.hl sha256=252fdb03d2c6a70b648445c53d9cfa9f72aacc81b4d7d48cd4348a8c80f15c73 *)
#flyspeck_needs "local/YRTAFYH.hl";;
(* 217 selected=flyspeck:text_formalization/local/WKEIDFT.hl sha256=f74b97e38d1bae6b3b5ee0ac6cc742c91a5dc0ae0cda9b221aa2d89ba4e8737b *)
#flyspeck_needs "local/WKEIDFT.hl";;
(* 218 selected=flyspeck:text_formalization/local/hexagons.hl sha256=977b4bbd72323078fd0197cbfa3902bc81019b149fe26007df9d25f2733fbd99 *)
#flyspeck_needs "local/hexagons.hl";;
(* 219 selected=flyspeck:text_formalization/local/IUNBUIG.hl sha256=f3af074951479a601b1e4c4f84330edfc655cbb70a3c48f8225437933150a66c *)
#flyspeck_needs "local/IUNBUIG.hl";;
(* 220 selected=flyspeck:text_formalization/local/OTMTOTJ.hl sha256=c8c93bb6696b0c07fe79cbac74b6bbda9446f05cb8f844a7966251cc750c75ca *)
#flyspeck_needs "local/OTMTOTJ.hl";;
(* 221 selected=flyspeck:text_formalization/local/HIJQAHA.hl sha256=22c076bc8e11f3b9f23e89d6117bc4bd0d3669bf00c08e5e98590206985312fc *)
#flyspeck_needs "local/HIJQAHA.hl";;
(* 222 selected=flyspeck:text_formalization/local/CNICGSF.hl sha256=37af43d90700b0ef7dc16539f6bd975f0b7bf57ee0392ef547243ea161e6fa5d *)
#flyspeck_needs "local/CNICGSF.hl";;
(* 223 selected=flyspeck:text_formalization/local/BKOSSGE.hl sha256=c38f760517df57282e3ac57348ea7c3e1a7037203be10c1ac2219e58e198b2a6 *)
#flyspeck_needs "local/BKOSSGE.hl";;
(* 224 selected=flyspeck:text_formalization/local/JOTSWIX.hl sha256=293277a82fb8ff79e660f6ea358ea6cd80fa35d681514fca79c9db75abe27da0 *)
#flyspeck_needs "local/JOTSWIX.hl";;
(* 225 selected=flyspeck:text_formalization/local/ARDBZYE.hl sha256=05da45cfa04fef5f8e3e81afd147e29cdffffd1f4617b93ca0306d467ba19917 *)
#flyspeck_needs "local/ARDBZYE.hl";;
(* 226 selected=flyspeck:text_formalization/local/AUEAHEH.hl sha256=1940067c4960386724e8144ad7f97f10d26136070d78a59db975b13f8d9e6d16 *)
#flyspeck_needs "local/AUEAHEH.hl";;
(* 227 selected=flyspeck:text_formalization/local/VASYYAU.hl sha256=7fd08a1ebd37cc79ef6d3b4aef7a2bcac39f03bc0d1e999087b010c3cb730a46 *)
#flyspeck_needs "local/VASYYAU.hl";;
(* 228 selected=flyspeck:text_formalization/local/MIQMCSN.hl sha256=28c2160ad8e3e71409868c4ef1dc4f0078aa99f6d5caad6f49a16fb8ab9084b7 *)
#flyspeck_needs "local/MIQMCSN.hl";;
(* 229 selected=flyspeck:text_formalization/local/JEJTVGB.hl sha256=e6fc3284eda723432c0080c78951758c82936498fac0b34c8fd78dff58d0519e *)
#flyspeck_needs "local/JEJTVGB.hl";;
(* 230 selected=flyspeck:formal_lp/hypermap/ssreflect/list_hypermap-compiled.hl sha256=9bc9f1f942bf055e0bea3fa10435b621e52458f435fc840bc670c51d648a67f5 *)
#flyspeck_needs "../formal_lp/hypermap/ssreflect/list_hypermap-compiled.hl";;
(* 231 selected=flyspeck:formal_lp/hypermap/ineqs/lp_gen_theory-compiled.hl sha256=aecda19251504176839a2ce11d95be727cacde86191805e13e48be25ad5d2010 *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_gen_theory-compiled.hl";;
(* 232 selected=flyspeck:formal_lp/hypermap/ssreflect/list_hypermap_iso-compiled.hl sha256=4570334c652aedda6e4c2aa6d9582b5e4737cd87989cf173fdea4867f3b88a9e *)
#flyspeck_needs "../formal_lp/hypermap/ssreflect/list_hypermap_iso-compiled.hl";;
(* 233 selected=flyspeck:formal_lp/hypermap/computations/more_theory-compiled.hl sha256=7990e6c09e98d13ef4de216b18e051eaf2283ceae04ceb31550685e244d8c6b2 *)
#flyspeck_needs "../formal_lp/hypermap/computations/more_theory-compiled.hl";;
(* 234 selected=flyspeck:text_formalization/local/RNSYJXM-compiled.hl sha256=3c859bb8b1a0eb20fbc5799ed84a9657b775675f29601b1e826a4c670244bc32 *)
#flyspeck_needs "local/RNSYJXM-compiled.hl";;
(* 235 selected=flyspeck:text_formalization/tame/tame_defs2.hl sha256=08b09d06788a737bca2c34644cbcf8eb23c5f660699e23ab68fc53037286faf8 *)
#flyspeck_needs "tame/tame_defs2.hl";;
(* 236 selected=flyspeck:text_formalization/tame/tame_list.hl sha256=d8b58c2881a6cfd67f66636056e325457c846828b77429a7d7a390ea794abcab *)
#flyspeck_needs "tame/tame_list.hl";;
(* 237 selected=flyspeck:text_formalization/tame/import_tame_classification.hl sha256=4996cf6a5660bdee0d10ae196fe44bce002dae9cdc05e139a3f8ae2c2b4c9a1b *)
#flyspeck_needs "tame/import_tame_classification.hl";;
(* 238 selected=flyspeck:text_formalization/tame/more_tame_concl.hl sha256=7e152e75a5e034dd3d0eebecd1c8138a85fda1b5d1a9947355545433d1778ec1 *)
#flyspeck_needs "tame/more_tame_concl.hl";;
(* 239 selected=flyspeck:text_formalization/tame/OXAXUCS.hl sha256=ae50be7218fcb2dff993fc47d58b1c660ea049b096950d9867e49418899bc471 *)
#flyspeck_needs "tame/OXAXUCS.hl";;
(* 240 selected=flyspeck:text_formalization/tame/ASFUTBF.hl sha256=da01b632fae22e61fc0ef7c2743c068c731614617ad3d5b4183a3ec1eb800e26 *)
#flyspeck_needs "tame/ASFUTBF.hl";;
(* 241 selected=flyspeck:text_formalization/tame/ELLLNYZ.hl sha256=424a7add82a9fc42462870cab3fb6e9b3fa2459f67554b49321cdd80980de94c *)
#flyspeck_needs "tame/ELLLNYZ.hl";;
(* 242 selected=flyspeck:text_formalization/tame/WMLNYMD.hl sha256=37a2725af5a489d2a6ccf3d2640910c87f4fbe180f36c53c9e8f23c28938f407 *)
#flyspeck_needs "tame/WMLNYMD.hl";;
(* 243 selected=flyspeck:text_formalization/tame/DPZGBYF.hl sha256=1771f96d887d3fa83c991e7a7040a76d03481086d6b35857d8f9ea39b901ba2f *)
#flyspeck_needs "tame/DPZGBYF.hl";;
(* 244 selected=flyspeck:text_formalization/tame/AUQTZYZ.hl sha256=854843b8cb07b73e5fb11734e6d2ed241fe259c21810b91144c319363ad9bd64 *)
#flyspeck_needs "tame/AUQTZYZ.hl";;
(* 245 selected=flyspeck:text_formalization/tame/AUQTZYZ_list.hl sha256=8a9b3d6622c6202257390e4e29856ba686a0140f0e3d6947504ecca30f501ddf *)
#flyspeck_needs "tame/AUQTZYZ_list.hl";;
(* 246 selected=flyspeck:text_formalization/tame/RXOKSKC.hl sha256=f247c7574609ab5b4c78a89c3aeabdafd8b9811056b87f2cb3a666a8a4c67d71 *)
#flyspeck_needs "tame/RXOKSKC.hl";;
(* 247 selected=flyspeck:text_formalization/tame/DANGEYJ.hl sha256=0307be200b55bed9d5d9695cf3ed856f03058358327632b893cbb5a84059067f *)
#flyspeck_needs "tame/DANGEYJ.hl";;
(* 248 selected=flyspeck:text_formalization/tame/JCAJYDU.hl sha256=d69f86b2021897044f1c9d0f17ea588ce18a396a010668c00a27106ebf65198b *)
#flyspeck_needs "tame/JCAJYDU.hl";;
(* 249 selected=flyspeck:text_formalization/tame/PWSSRAT.hl sha256=5f553529300c75f08dde82d01e4d12bad274927a33b9383aaee23edb7da5b856 *)
#flyspeck_needs "tame/PWSSRAT.hl";;
(* 250 selected=flyspeck:text_formalization/tame/OHCGKFU.hl sha256=5ed8fabbd0e7d9c1bc9a5a5ee36fdecf2d5671a9a539b5964a283e274531aa56 *)
#flyspeck_needs "tame/OHCGKFU.hl";;
(* 251 selected=flyspeck:text_formalization/tame/PPLHULJ.hl sha256=d06e7d2a322a0eb7cf5e427eb998a1893dba27e95c7912f8a47f8a4f98326c6e *)
#flyspeck_needs "tame/PPLHULJ.hl";;
(* 252 selected=flyspeck:text_formalization/tame/NCVIBWU.hl sha256=6206c80859846ec2e6c316ef726515a42e1090d40890ea63b3610d9e0ca968a4 *)
#flyspeck_needs "tame/NCVIBWU.hl";;
(* 253 selected=flyspeck:text_formalization/tame/QCDVKEA.hl sha256=d903856d87313a13fb6c28975264b019fbcad5849ca5d03a2ffab12489c5cc9c *)
#flyspeck_needs "tame/QCDVKEA.hl";;
(* 254 selected=flyspeck:text_formalization/tame/PBFLHET.hl sha256=819fc259303fb1959edf4f673079563847b4f31e12dfa1875e94c5e3308a6ede *)
#flyspeck_needs "tame/PBFLHET.hl";;
(* 255 selected=flyspeck:text_formalization/tame/PNXVWFS.hl sha256=2ea5c700f972ea395dd4bf60966f310d56004d5fc485150e01ae4e9d5e7e73b5 *)
#flyspeck_needs "tame/PNXVWFS.hl";;
(* 256 selected=flyspeck:text_formalization/tame/DIOWAAS.hl sha256=0ff84cfbc9ad82997a5f0d4e69d2c76ea6dcdb214bd38bc3bfe0d4fd96f6585d *)
#flyspeck_needs "tame/DIOWAAS.hl";;
(* 257 selected=flyspeck:text_formalization/tame/RYIUUVK.hl sha256=0a97715c29ffefbf3e8b755040a350a816118dfc8c3dd637f227f62a0167c509 *)
#flyspeck_needs "tame/RYIUUVK.hl";;
(* 258 selected=flyspeck:text_formalization/tame/KBWPBHQ.hl sha256=b314a566445bd16a11d52fc2420c094b010632b2333d8dd2ec708636663448a1 *)
#flyspeck_needs "tame/KBWPBHQ.hl";;
(* 259 selected=flyspeck:text_formalization/tame/MEEIXJO.hl sha256=8347ac457878d27f6aabb719bcae4668b9ff52efaa111c9ab5a29114e22aeae1 *)
#flyspeck_needs "tame/MEEIXJO.hl";;
(* 260 selected=flyspeck:text_formalization/tame/OBDATYB.hl sha256=3b9f1cc6f5fda4fca4dc97200a9edb3d15b473a680169c07950100b2d06289a0 *)
#flyspeck_needs "tame/OBDATYB.hl";;
(* 261 selected=flyspeck:text_formalization/tame/LEBHIRJ.hl sha256=1740c206c6c24fdb841b1914fba5ab3d3969066a7c58eca167c29383ec5dc9d2 *)
#flyspeck_needs "tame/LEBHIRJ.hl";;
(* 262 selected=flyspeck:text_formalization/tame/HOJODCM.hl sha256=c3f94f3d311f8c49cb75065f6d4de733b6ee695964922c8d118a23fccb5a9fc1 *)
#flyspeck_needs "tame/HOJODCM.hl";;
(* 263 selected=flyspeck:text_formalization/tame/AQ1.hl sha256=9ca2451173d87d55017068f3ad530aa642a79cebe174efbe5e5b6753c01a815a *)
#flyspeck_needs "tame/AQ1.hl";;
(* 264 selected=flyspeck:text_formalization/tame/AQ23.hl sha256=41b0aa9c1ef5299da9138912eeb270e40f35588e440402492fa54fd7b6db4f4d *)
#flyspeck_needs "tame/AQ23.hl";;
(* 265 selected=flyspeck:text_formalization/tame/AQ4.hl sha256=812c6ee5c3854341eb6bf396ed461431bf272fb307ea2c3b37c56f08a8f89a4e *)
#flyspeck_needs "tame/AQ4.hl";;
(* 266 selected=flyspeck:text_formalization/tame/AQ56.hl sha256=0731c2a46ab7480b331454bc0f7f52a2b0e2d2c067d2aed1aa306df1fe5e6f7b *)
#flyspeck_needs "tame/AQ56.hl";;
(* 267 selected=flyspeck:text_formalization/tame/AQ7.hl sha256=a24d3cb19c5a3a61cdeba701677c321dca2e977691ad89b3ad25555efa742331 *)
#flyspeck_needs "tame/AQ7.hl";;
(* 268 selected=flyspeck:text_formalization/tame/AQ8.hl sha256=37129d8cfa83a3cc057be3ae89304ffbc684fd8f2366b039a11042dc805d0c2c *)
#flyspeck_needs "tame/AQ8.hl";;
(* 269 selected=flyspeck:text_formalization/tame/AQ9.hl sha256=5dc33eb89d04da7fc7ee203d9c8a3e4a50de778010ecf4bc70df845433f42545 *)
#flyspeck_needs "tame/AQ9.hl";;
(* 270 selected=flyspeck:text_formalization/tame/AQ10.hl sha256=627824d5af6b6ed2b80ae2b14ff9b30babf8f2578cf811c0d6ade9babe3b7503 *)
#flyspeck_needs "tame/AQ10.hl";;
(* 271 selected=flyspeck:text_formalization/tame/AQ11.hl sha256=43d5a3a16ebd6a77adcc61a66719324851c83ba52731240e9c6cf0e9c5dd6c64 *)
#flyspeck_needs "tame/AQ11.hl";;
(* 272 selected=flyspeck:text_formalization/tame/AQ12.hl sha256=d5cf605b76e0790e435d775e78f7c8e03e11f0ed40a6bd9fae3b1f5af2d1a12c *)
#flyspeck_needs "tame/AQ12.hl";;
(* 273 selected=flyspeck:text_formalization/tame/AQ13.hl sha256=67d470a7d3b070126fb0327343adad06ec125099787f1bd1c90559e538d959ba *)
#flyspeck_needs "tame/AQ13.hl";;
(* 274 selected=flyspeck:text_formalization/tame/reduction1.hl sha256=a40d60c57f2e85791b19545fbba1106c73a59649dd698c218734ca5aefe66429 *)
#flyspeck_needs "tame/reduction1.hl";;
(* 275 selected=flyspeck:text_formalization/tame/reduction2.hl sha256=236405bd79133ec4f251993972950907dabd440c6d1a15caf9a7d2c2d49836b2 *)
#flyspeck_needs "tame/reduction2.hl";;
(* 276 selected=flyspeck:text_formalization/tame/more_lemma1.hl sha256=dadc5eda51cd3552a94612249d438f702ca749550c9653bc0ece1bd4c35d8eca *)
#flyspeck_needs "tame/more_lemma1.hl";;
(* 277 selected=flyspeck:text_formalization/tame/reduction3.hl sha256=9f4b59639ff2c692553637c8aa41f7b5c9a8093bd8e444bfec0b6e14653f5713 *)
#flyspeck_needs "tame/reduction3.hl";;
(* 278 selected=flyspeck:text_formalization/tame/more_lemma2.hl sha256=1dbdabd739d41755288029b036d169b51f4188bc0173c15e85c99ef51509cd53 *)
#flyspeck_needs "tame/more_lemma2.hl";;
(* 279 selected=flyspeck:text_formalization/tame/reduction4.hl sha256=51fa1361d42ecdca85d4e0f094e12887c5bf745a9fe6363f9c87a43ffe045b1a *)
#flyspeck_needs "tame/reduction4.hl";;
(* 280 selected=flyspeck:text_formalization/tame/betwn_corek_z_x.hl sha256=e26c0a51a4e989532f851c696c908dcccdd0db8e3c34b7439cf7780ca503a1de *)
#flyspeck_needs "tame/betwn_corek_z_x.hl";;
(* 281 selected=flyspeck:text_formalization/tame/betwn_core0_z_y.hl sha256=93c0a04a508b7fcb479bcb8a24088df432c5e08a41a7e7bdf2cb07ce01511251 *)
#flyspeck_needs "tame/betwn_core0_z_y.hl";;
(* 282 selected=flyspeck:text_formalization/tame/reduction5.hl sha256=b1210a0c9d7e57c27273336e87f7da1440ef7cd31fc8c70b5e3faa80860c3a99 *)
#flyspeck_needs "tame/reduction5.hl";;
(* 283 selected=flyspeck:formal_lp/hypermap/ineqs/lp_ineqs_defs.hl sha256=1013104c8691fc94b3b4202d554cc518ae934c0e4a3b2579f66adce6f0432b6f *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_ineqs_defs.hl";;
(* 284 selected=flyspeck:formal_lp/ineqs/constants_approx.hl sha256=1a4271b07f67034781400fc06abc374b94cbc9c85433fb78ba2a32c89283dccb *)
#flyspeck_needs "../formal_lp/ineqs/constants_approx.hl";;
(* 285 selected=flyspeck:formal_lp/hypermap/ineqs/lp_ineqs_proofs-compiled.hl sha256=660fd87e5ef3ffbcc623c438a5d719456b558f9e51c198197ca6496c514fae4c *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_ineqs_proofs-compiled.hl";;
(* 286 selected=flyspeck:formal_lp/hypermap/ineqs/lp_main_estimate-compiled.hl sha256=10e6a449605eab5f209d942e7e192ced7c70cba66f616acc314be1538ac0f5aa *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_main_estimate-compiled.hl";;
(* 287 selected=flyspeck:formal_lp/hypermap/ineqs/lp_ineqs_quads-compiled.hl sha256=879bb59c3e98ac8c9e2d14deabaede782082178ff72bd0838994087c9015976c *)
#flyspeck_needs "../formal_lp/hypermap/ineqs/lp_ineqs_quads-compiled.hl";;
(* 288 selected=flyspeck:text_formalization/tame/ssreflect/KCBLRQC-compiled.hl sha256=22a17578d5edeb7ea8f44bda56b751ea54085948c1f0b2ad9488d1b3faa1bd32 *)
#flyspeck_needs "tame/ssreflect/KCBLRQC-compiled.hl";;
(* 289 selected=flyspeck:text_formalization/tame/ssreflect/MQMSMAB-compiled.hl sha256=ab3f207cd56c575e18506931d23cdc69f153070f4e2f71c74f90ba793283288d *)
#flyspeck_needs "tame/ssreflect/MQMSMAB-compiled.hl";;
(* 290 selected=flyspeck:text_formalization/packing/flyspeck_devol.hl sha256=391911f87e472b48e4f2e394ce9c929620752c972ff52f69962d255306e8676a *)
#flyspeck_needs "packing/flyspeck_devol.hl";;

(* stratum: final_assembly *)
(* 291 selected=flyspeck:text_formalization/general/kepler_spec.hl sha256=c0ea2b9b8671a29be035c9e128faa9f6161f97c2c8a33188561a52b7697e1d32 *)
#flyspeck_needs "general/kepler_spec.hl";;
(* 292 selected=flyspeck:text_formalization/general/the_main_statement.hl sha256=1e0171dd49125995da6e9f183e6de3eb802ac0eae42a913d5619374108e11f2a *)
#flyspeck_needs "general/the_main_statement.hl";;
(* 293 selected=flyspeck:text_formalization/general/audit_formal_proof.hl sha256=4edde81228d043135e8ad08e31f6d6b345985c197a3f8b7e3d684c72382f0bfc *)
#flyspeck_needs "general/audit_formal_proof.hl";;
(* 294 selected=flyspeck:text_formalization/general/the_kepler_conjecture.hl sha256=d2a45bd4fca8c4f7f705736bf5c34cdbb60e7182226102560b1c5bc3369de3c7 *)
#flyspeck_needs "general/the_kepler_conjecture.hl";;
(* 295 selected=flyspeck:text_formalization/general/serialization.hl sha256=fe7f414d6e72a2c838a81b59af15494a1e9f6a5118f9ec0cd1f6ade11a939eed *)
#flyspeck_needs "general/serialization.hl";;
(* 296 selected=flyspeck:text_formalization/nonlinear/mk_all_ineq.hl sha256=99d005141807102b57a6daee0c4e512691d9846996f9b2331dd7ff946b695c11 *)
#flyspeck_needs "nonlinear/mk_all_ineq.hl";;
